export enum CategoriaComentario {
  ELOGIO = "ELOGIO",
  CRITICA = "CRITICA",
  SUGESTAO = "SUGESTAO",
  RECLAMACAO = "RECLAMACAO",
  DUVIDA = "DUVIDA",
  FALTA_DE_COLETA = "FALTA_DE_COLETA",
  INFORMACAO_ERRADA = "INFORMACAO_ERRADA",
  OUTRO = "OUTRO",
}
